### ISSUE TITLE
Crash just after pressing ESC sometimes (`NoSuchElementException`)

### ISSUE THREAD

**Issue by ItzSkyReed** [mrbuilder1961/WheresMyChatHistory#178]
### Description
I just press ESC and minecraft crashes

### How to reproduce
I don't know exactly, I got it once

### Expected result
Nothing special should happend

### Log file link
https://mclo.gs/ekjJGfz

### Specs and Details
Required information:
- Computer OS - Win 11
- Mod version 210.6.5
- Fabric and API versions Latest
- YetAnotherConfigLib and Mod Menu versions (if installed)    3.5.0+1.21-fabric
- List of all installed mods (can be a list *copied* from a log file **OR** a screenshot of the mods folder) Inside Logs

Optional but suggested information:
- `chatpatches.json` file (if pasted use the format: \`\`\`json\n\<config data>\n\`\`\`) [chatpatches.json](https://github.com/user-attachments/files/15950236/chatpatches.json)
- `chatlog.json` file (DO NOT PASTE)

### Additional context
 No info, sorry

**Comment by yilnea** [comment]
Running into this issue as well on 1.21

**Comment by mrbuilder1961** [comment]
okay this *should* be fixed in the testing branch (specifically [here](https://github.com/mrbuilder1961/ChatPatches/commit/05e5f6fc932d8478b98a504c9141e686be7737c8)) but i can probably carry the fix over soon. thanks!

**Comment by mrbuilder1961** [comment]
should be fixed in [`210.6.5.1`](https://modrinth.com/mod/chatpatches/version/210.6.5.1) !

**Comment by yepidoodles** [comment]
[crash-2024-07-21_01.13.27-client.txt](https://github.com/user-attachments/files/16322674/crash-2024-07-21_01.13.27-client.txt)

Seems this crash is still occuring in 210.6.5.1, a friend also got this exact same report after pressing esc with this mod

**Comment by ItzSkyReed** [comment]
@mrbuilder1961

**Comment by mrbuilder1961** [comment]
this issue is actually fixed in the latest release.

> [crash-2024-07-21_01.13.27-client.txt](https://mclo.gs/ldsSLA6)
> 
> Seems this crash is still occuring in 210.6.5.1, a friend also got this exact same report after pressing esc with this mod

however, the exception titled in this new crash report is the same as the original, but with a different source. that issue is being tracked in #180.
